const NIFTY_500: StockMeta[] = [
  { symbol: "360ONE", sector: "Financial Services" },
  { symbol: "3MINDIA", sector: "Diversified" },
  { symbol: "AADHARHFC", sector: "Financial Services" },
  { symbol: "AARTIIND", sector: "Chemicals" },
  { symbol: "AAVAS", sector: "Financial Services" },
  { symbol: "ABB", sector: "Capital Goods" },
  { symbol: "ABBOTINDIA", sector: "Healthcare" },
  { symbol: "ABCAPITAL", sector: "Financial Services" },
  { symbol: "ABFRL", sector: "Consumer Services" },
  { symbol: "ABLBL", sector: "Consumer Services" },
  { symbol: "ABREL", sector: "Forest Materials" },
  { symbol: "ABSLAMC", sector: "Financial Services" },
  { symbol: "ACC", sector: "Construction Materials" },
  { symbol: "ACE", sector: "Capital Goods" },
  { symbol: "ACMESOLAR", sector: "Power" },
  { symbol: "ADANIENSOL", sector: "Power" },
  { symbol: "ADANIENT", sector: "Metals & Mining" },
  { symbol: "ADANIGREEN", sector: "Power" },
  { symbol: "ADANIPORTS", sector: "Services" },
  { symbol: "ADANIPOWER", sector: "Power" },
  { symbol: "AEGISLOG", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "AEGISVOPAK", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "AFCONS", sector: "Construction" },
  { symbol: "AFFLE", sector: "Information Technology" },
  { symbol: "AGARWALEYE", sector: "Healthcare" },
  { symbol: "AIAENG", sector: "Capital Goods" },
  { symbol: "AIIL", sector: "Financial Services" },
  { symbol: "AJANTPHARM", sector: "Healthcare" },
  { symbol: "AKUMS", sector: "Healthcare" },
  { symbol: "AKZOINDIA", sector: "Consumer Durables" },
  { symbol: "ALKEM", sector: "Healthcare" },
  { symbol: "ALKYLAMINE", sector: "Chemicals" },
  { symbol: "ALOKINDS", sector: "Textiles" },
  { symbol: "AMBER", sector: "Consumer Durables" },
  { symbol: "AMBUJACEM", sector: "Construction Materials" },
  { symbol: "ANANDRATHI", sector: "Financial Services" },
  { symbol: "ANANTRAJ", sector: "Realty" },
  { symbol: "ANGELONE", sector: "Financial Services" },
  { symbol: "APARINDS", sector: "Capital Goods" },
  { symbol: "APLAPOLLO", sector: "Capital Goods" },
  { symbol: "APLLTD", sector: "Healthcare" },
  { symbol: "APOLLOHOSP", sector: "Healthcare" },
  { symbol: "APOLLOTYRE", sector: "Automobile and Auto Components" },
  { symbol: "APTUS", sector: "Financial Services" },
  { symbol: "ARE&M", sector: "Automobile and Auto Components" },
  { symbol: "ASAHIINDIA", sector: "Automobile and Auto Components" },
  { symbol: "ASHOKLEY", sector: "Capital Goods" },
  { symbol: "ASIANPAINT", sector: "Consumer Durables" },
  { symbol: "ASTERDM", sector: "Healthcare" },
  { symbol: "ASTRAL", sector: "Capital Goods" },
  { symbol: "ASTRAZEN", sector: "Healthcare" },
  { symbol: "ATGL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "ATHERENERG", sector: "Automobile and Auto Components" },
  { symbol: "ATUL", sector: "Chemicals" },
  { symbol: "AUBANK", sector: "Financial Services" },
  { symbol: "AUROPHARMA", sector: "Healthcare" },
  { symbol: "AWL", sector: "Fast Moving Consumer Goods" },
  { symbol: "AXISBANK", sector: "Financial Services" },
  { symbol: "BAJAJ-AUTO", sector: "Automobile and Auto Components" },
  { symbol: "BAJAJFINSV", sector: "Financial Services" },
  { symbol: "BAJAJHFL", sector: "Financial Services" },
  { symbol: "BAJAJHLDNG", sector: "Financial Services" },
  { symbol: "BAJFINANCE", sector: "Financial Services" },
  { symbol: "BALKRISIND", sector: "Automobile and Auto Components" },
  { symbol: "BALRAMCHIN", sector: "Fast Moving Consumer Goods" },
  { symbol: "BANDHANBNK", sector: "Financial Services" },
  { symbol: "BANKBARODA", sector: "Financial Services" },
  { symbol: "BANKINDIA", sector: "Financial Services" },
  { symbol: "BASF", sector: "Chemicals" },
  { symbol: "BATAINDIA", sector: "Consumer Durables" },
  { symbol: "BAYERCROP", sector: "Chemicals" },
  { symbol: "BBTC", sector: "Fast Moving Consumer Goods" },
  { symbol: "BDL", sector: "Capital Goods" },
  { symbol: "BEL", sector: "Capital Goods" },
  { symbol: "BEML", sector: "Capital Goods" },
  { symbol: "BERGEPAINT", sector: "Consumer Durables" },
  { symbol: "BHARATFORG", sector: "Automobile and Auto Components" },
  { symbol: "BHARTIARTL", sector: "Telecommunication" },
  { symbol: "BHARTIHEXA", sector: "Telecommunication" },
  { symbol: "BHEL", sector: "Capital Goods" },
  { symbol: "BIKAJI", sector: "Fast Moving Consumer Goods" },
  { symbol: "BIOCON", sector: "Healthcare" },
  { symbol: "BLS", sector: "Consumer Services" },
  { symbol: "BLUEDART", sector: "Services" },
  { symbol: "BLUEJET", sector: "Healthcare" },
  { symbol: "BLUESTARCO", sector: "Consumer Durables" },
  { symbol: "BOSCHLTD", sector: "Automobile and Auto Components" },
  { symbol: "BPCL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "BRIGADE", sector: "Realty" },
  { symbol: "BRITANNIA", sector: "Fast Moving Consumer Goods" },
  { symbol: "BSE", sector: "Financial Services" },
  { symbol: "BSOFT", sector: "Information Technology" },
  { symbol: "CAMPUS", sector: "Consumer Durables" },
  { symbol: "CAMS", sector: "Financial Services" },
  { symbol: "CANBK", sector: "Financial Services" },
  { symbol: "CANFINHOME", sector: "Financial Services" },
  { symbol: "CAPLIPOINT", sector: "Healthcare" },
  { symbol: "CARBORUNIV", sector: "Capital Goods" },
  { symbol: "CASTROLIND", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "CCL", sector: "Fast Moving Consumer Goods" },
  { symbol: "CDSL", sector: "Financial Services" },
  { symbol: "CEATLTD", sector: "Automobile and Auto Components" },
  { symbol: "CENTRALBK", sector: "Financial Services" },
  { symbol: "CENTURYPLY", sector: "Consumer Durables" },
  { symbol: "CERA", sector: "Consumer Durables" },
  { symbol: "CESC", sector: "Power" },
  { symbol: "CGCL", sector: "Financial Services" },
  { symbol: "CGPOWER", sector: "Capital Goods" },
  { symbol: "CHALET", sector: "Consumer Services" },
  { symbol: "CHAMBLFERT", sector: "Chemicals" },
  { symbol: "CHENNPETRO", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "CHOICEIN", sector: "Financial Services" },
  { symbol: "CHOLAFIN", sector: "Financial Services" },
  { symbol: "CHOLAHLDNG", sector: "Financial Services" },
  { symbol: "CIPLA", sector: "Healthcare" },
  { symbol: "CLEAN", sector: "Chemicals" },
  { symbol: "COALINDIA", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "COCHINSHIP", sector: "Capital Goods" },
  { symbol: "COFORGE", sector: "Information Technology" },
  { symbol: "COHANCE", sector: "Healthcare" },
  { symbol: "COLPAL", sector: "Fast Moving Consumer Goods" },
  { symbol: "CONCOR", sector: "Services" },
  { symbol: "CONCORDBIO", sector: "Healthcare" },
  { symbol: "COROMANDEL", sector: "Chemicals" },
  { symbol: "CRAFTSMAN", sector: "Automobile and Auto Components" },
  { symbol: "CREDITACC", sector: "Financial Services" },
  { symbol: "CRISIL", sector: "Financial Services" },
  { symbol: "CROMPTON", sector: "Consumer Durables" },
  { symbol: "CUB", sector: "Financial Services" },
  { symbol: "CUMMINSIND", sector: "Capital Goods" },
  { symbol: "CYIENT", sector: "Information Technology" },
  { symbol: "DABUR", sector: "Fast Moving Consumer Goods" },
  { symbol: "DALBHARAT", sector: "Construction Materials" },
  { symbol: "DATAPATTNS", sector: "Capital Goods" },
  { symbol: "DBREALTY", sector: "Consumer Services" },
  { symbol: "DCMSHRIRAM", sector: "Diversified" },
  { symbol: "DEEPAKFERT", sector: "Chemicals" },
  { symbol: "DEEPAKNTR", sector: "Chemicals" },
  { symbol: "DELHIVERY", sector: "Services" },
  { symbol: "DEVYANI", sector: "Consumer Services" },
  { symbol: "DIVISLAB", sector: "Healthcare" },
  { symbol: "DIXON", sector: "Consumer Durables" },
  { symbol: "DLF", sector: "Realty" },
  { symbol: "DMART", sector: "Consumer Services" },
  { symbol: "DOMS", sector: "Fast Moving Consumer Goods" },
  { symbol: "DRREDDY", sector: "Healthcare" },
  { symbol: "ECLERX", sector: "Services" },
  { symbol: "EICHERMOT", sector: "Automobile and Auto Components" },
  { symbol: "EIDPARRY", sector: "Fast Moving Consumer Goods" },
  { symbol: "EIHOTEL", sector: "Consumer Services" },
  { symbol: "ELECON", sector: "Capital Goods" },
  { symbol: "ELGIEQUIP", sector: "Capital Goods" },
  { symbol: "EMAMILTD", sector: "Fast Moving Consumer Goods" },
  { symbol: "EMCURE", sector: "Healthcare" },
  { symbol: "ENDURANCE", sector: "Automobile and Auto Components" },
  { symbol: "ENGINERSIN", sector: "Construction" },
  { symbol: "ENRIN", sector: "Capital Goods" },
  { symbol: "ERIS", sector: "Healthcare" },
  { symbol: "ESCORTS", sector: "Capital Goods" },
  { symbol: "ETERNAL", sector: "Consumer Services" },
  { symbol: "EXIDEIND", sector: "Automobile and Auto Components" },
  { symbol: "FACT", sector: "Chemicals" },
  { symbol: "FEDERALBNK", sector: "Financial Services" },
  { symbol: "FINCABLES", sector: "Capital Goods" },
  { symbol: "FINPIPE", sector: "Capital Goods" },
  { symbol: "FIRSTCRY", sector: "Consumer Services" },
  { symbol: "FIVESTAR", sector: "Financial Services" },
  { symbol: "FLUOROCHEM", sector: "Chemicals" },
  { symbol: "FORCEMOT", sector: "Automobile and Auto Components" },
  { symbol: "FORTIS", sector: "Healthcare" },
  { symbol: "FSL", sector: "Services" },
  { symbol: "GAIL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "GESHIP", sector: "Services" },
  { symbol: "GICRE", sector: "Financial Services" },
  { symbol: "GILLETTE", sector: "Fast Moving Consumer Goods" },
  { symbol: "GLAND", sector: "Healthcare" },
  { symbol: "GLAXO", sector: "Healthcare" },
  { symbol: "GLENMARK", sector: "Healthcare" },
  { symbol: "GMDCLTD", sector: "Metals & Mining" },
  { symbol: "GMRAIRPORT", sector: "Services" },
  { symbol: "GODFRYPHLP", sector: "Fast Moving Consumer Goods" },
  { symbol: "GODIGIT", sector: "Financial Services" },
  { symbol: "GODREJAGRO", sector: "Fast Moving Consumer Goods" },
  { symbol: "GODREJCP", sector: "Fast Moving Consumer Goods" },
  { symbol: "GODREJIND", sector: "Diversified" },
  { symbol: "GODREJPROP", sector: "Realty" },
  { symbol: "GPIL", sector: "Capital Goods" },
  { symbol: "GRANULES", sector: "Healthcare" },
  { symbol: "GRAPHITE", sector: "Capital Goods" },
  { symbol: "GRASIM", sector: "Construction Materials" },
  { symbol: "GRAVITA", sector: "Metals & Mining" },
  { symbol: "GRSE", sector: "Capital Goods" },
  { symbol: "GSPL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "GUJGASLTD", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "GVT&D", sector: "Capital Goods" },
  { symbol: "HAL", sector: "Capital Goods" },
  { symbol: "HAPPSTMNDS", sector: "Information Technology" },
  { symbol: "HAVELLS", sector: "Consumer Durables" },
  { symbol: "HBLENGINE", sector: "Capital Goods" },
  { symbol: "HCLTECH", sector: "Information Technology" },
  { symbol: "HDFCAMC", sector: "Financial Services" },
  { symbol: "HDFCBANK", sector: "Financial Services" },
  { symbol: "HDFCLIFE", sector: "Financial Services" },
  { symbol: "HEG", sector: "Capital Goods" },
  { symbol: "HEROMOTOCO", sector: "Automobile and Auto Components" },
  { symbol: "HEXT", sector: "Information Technology" },
  { symbol: "HFCL", sector: "Telecommunication" },
  { symbol: "HINDALCO", sector: "Metals & Mining" },
  { symbol: "HINDCOPPER", sector: "Metals & Mining" },
  { symbol: "HINDPETRO", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "HINDUNILVR", sector: "Fast Moving Consumer Goods" },
  { symbol: "HINDZINC", sector: "Metals & Mining" },
  { symbol: "HOMEFIRST", sector: "Financial Services" },
  { symbol: "HONASA", sector: "Fast Moving Consumer Goods" },
  { symbol: "HONAUT", sector: "Capital Goods" },
  { symbol: "HSCL", sector: "Chemicals" },
  { symbol: "HUDCO", sector: "Financial Services" },
  { symbol: "HYUNDAI", sector: "Automobile and Auto Components" },
  { symbol: "ICICIBANK", sector: "Financial Services" },
  { symbol: "ICICIGI", sector: "Financial Services" },
  { symbol: "ICICIPRULI", sector: "Financial Services" },
  { symbol: "IDBI", sector: "Financial Services" },
  { symbol: "IDEA", sector: "Telecommunication" },
  { symbol: "IDFCFIRSTB", sector: "Financial Services" },
  { symbol: "IEX", sector: "Financial Services" },
  { symbol: "IFCI", sector: "Financial Services" },
  { symbol: "IGIL", sector: "Services" },
  { symbol: "IGL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "IIFL", sector: "Financial Services" },
  { symbol: "IKS", sector: "Information Technology" },
  { symbol: "INDGN", sector: "Healthcare" },
  { symbol: "INDHOTEL", sector: "Consumer Services" },
  { symbol: "INDIACEM", sector: "Construction Materials" },
  { symbol: "INDIAMART", sector: "Consumer Services" },
  { symbol: "INDIANB", sector: "Financial Services" },
  { symbol: "INDIGO", sector: "Services" },
  { symbol: "INDUSINDBK", sector: "Financial Services" },
  { symbol: "INDUSTOWER", sector: "Telecommunication" },
  { symbol: "INFY", sector: "Information Technology" },
  { symbol: "INOXINDIA", sector: "Capital Goods" },
  { symbol: "INOXWIND", sector: "Capital Goods" },
  { symbol: "INTELLECT", sector: "Information Technology" },
  { symbol: "IOB", sector: "Financial Services" },
  { symbol: "IOC", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "IPCALAB", sector: "Healthcare" },
  { symbol: "IRB", sector: "Construction" },
  { symbol: "IRCON", sector: "Construction" },
  { symbol: "IRCTC", sector: "Consumer Services" },
  { symbol: "IREDA", sector: "Financial Services" },
  { symbol: "IRFC", sector: "Financial Services" },
  { symbol: "ITC", sector: "Fast Moving Consumer Goods" },
  { symbol: "ITCHOTELS", sector: "Consumer Services" },
  { symbol: "ITI", sector: "Telecommunication" },
  { symbol: "J&KBANK", sector: "Financial Services" },
  { symbol: "JBCHEPHARM", sector: "Healthcare" },
  { symbol: "JBMA", sector: "Automobile and Auto Components" },
  { symbol: "JINDALSAW", sector: "Capital Goods" },
  { symbol: "JINDALSTEL", sector: "Metals & Mining" },
  { symbol: "JIOFIN", sector: "Financial Services" },
  { symbol: "JKCEMENT", sector: "Construction Materials" },
  { symbol: "JKTYRE", sector: "Automobile and Auto Components" },
  { symbol: "JMFINANCIL", sector: "Financial Services" },
  { symbol: "JPPOWER", sector: "Power" },
  { symbol: "JSL", sector: "Metals & Mining" },
  { symbol: "JSWCEMENT", sector: "Construction Materials" },
  { symbol: "JSWENERGY", sector: "Power" },
  { symbol: "JSWINFRA", sector: "Services" },
  { symbol: "JSWSTEEL", sector: "Metals & Mining" },
  { symbol: "JUBLFOOD", sector: "Consumer Services" },
  { symbol: "JUBLINGREA", sector: "Chemicals" },
  { symbol: "JUBLPHARMA", sector: "Healthcare" },
  { symbol: "JWL", sector: "Capital Goods" },
  { symbol: "JYOTHYLAB", sector: "Fast Moving Consumer Goods" },
  { symbol: "JYOTICNC", sector: "Capital Goods" },
  { symbol: "KAJARIACER", sector: "Consumer Durables" },
  { symbol: "KALYANKJIL", sector: "Consumer Durables" },
  { symbol: "KARURVYSYA", sector: "Financial Services" },
  { symbol: "KAYNES", sector: "Capital Goods" },
  { symbol: "KEC", sector: "Construction" },
  { symbol: "KEI", sector: "Capital Goods" },
  { symbol: "KFINTECH", sector: "Financial Services" },
  { symbol: "KIMS", sector: "Healthcare" },
  { symbol: "KIRLOSBROS", sector: "Capital Goods" },
  { symbol: "KIRLOSENG", sector: "Capital Goods" },
  { symbol: "KOTAKBANK", sector: "Financial Services" },
  { symbol: "KPIL", sector: "Construction" },
  { symbol: "KPITTECH", sector: "Information Technology" },
  { symbol: "KPRMILL", sector: "Textiles" },
  { symbol: "KSB", sector: "Capital Goods" },
  { symbol: "LALPATHLAB", sector: "Healthcare" },
  { symbol: "LATENTVIEW", sector: "Information Technology" },
  { symbol: "LAURUSLABS", sector: "Healthcare" },
  { symbol: "LEMONTREE", sector: "Consumer Services" },
  { symbol: "LICHSGFIN", sector: "Financial Services" },
  { symbol: "LICI", sector: "Financial Services" },
  { symbol: "LINDEINDIA", sector: "Chemicals" },
  { symbol: "LLOYDSME", sector: "Metals & Mining" },
  { symbol: "LODHA", sector: "Realty" },
  { symbol: "LT", sector: "Construction" },
  { symbol: "LTF", sector: "Financial Services" },
  { symbol: "LTFOODS", sector: "Fast Moving Consumer Goods" },
  { symbol: "LTM", sector: "Information Technology" },
  { symbol: "LTTS", sector: "Information Technology" },
  { symbol: "LUPIN", sector: "Healthcare" },
  { symbol: "M&M", sector: "Automobile and Auto Components" },
  { symbol: "M&MFIN", sector: "Financial Services" },
  { symbol: "MAHABANK", sector: "Financial Services" },
  { symbol: "MAHSCOOTER", sector: "Financial Services" },
  { symbol: "MAHSEAMLES", sector: "Capital Goods" },
  { symbol: "MANAPPURAM", sector: "Financial Services" },
  { symbol: "MANKIND", sector: "Healthcare" },
  { symbol: "MANYAVAR", sector: "Consumer Services" },
  { symbol: "MAPMYINDIA", sector: "Information Technology" },
  { symbol: "MARICO", sector: "Fast Moving Consumer Goods" },
  { symbol: "MARUTI", sector: "Automobile and Auto Components" },
  { symbol: "MAXHEALTH", sector: "Healthcare" },
  { symbol: "MAZDOCK", sector: "Capital Goods" },
  { symbol: "MCX", sector: "Financial Services" },
  { symbol: "MEDANTA", sector: "Healthcare" },
  { symbol: "METROPOLIS", sector: "Healthcare" },
  { symbol: "MFSL", sector: "Financial Services" },
  { symbol: "MGL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "MINDACORP", sector: "Automobile and Auto Components" },
  { symbol: "MMTC", sector: "Services" },
  { symbol: "MOTHERSON", sector: "Automobile and Auto Components" },
  { symbol: "MOTILALOFS", sector: "Financial Services" },
  { symbol: "MPHASIS", sector: "Information Technology" },
  { symbol: "MRF", sector: "Automobile and Auto Components" },
  { symbol: "MRPL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "MSUMI", sector: "Automobile and Auto Components" },
  { symbol: "MUTHOOTFIN", sector: "Financial Services" },
  { symbol: "NAM-INDIA", sector: "Financial Services" },
  { symbol: "NATCOPHARM", sector: "Healthcare" },
  { symbol: "NATIONALUM", sector: "Metals & Mining" },
  { symbol: "NAUKRI", sector: "Consumer Services" },
  { symbol: "NAVA", sector: "Power" },
  { symbol: "NAVINFLUOR", sector: "Chemicals" },
  { symbol: "NBCC", sector: "Construction" },
  { symbol: "NCC", sector: "Construction" },
  { symbol: "NESTLEIND", sector: "Fast Moving Consumer Goods" },
  { symbol: "NETWEB", sector: "Information Technology" },
  { symbol: "NEULANDLAB", sector: "Healthcare" },
  { symbol: "NEWGEN", sector: "Information Technology" },
  { symbol: "NH", sector: "Healthcare" },
  { symbol: "NHPC", sector: "Power" },
  { symbol: "NIACL", sector: "Financial Services" },
  { symbol: "NIVABUPA", sector: "Financial Services" },
  { symbol: "NLCINDIA", sector: "Power" },
  { symbol: "NMDC", sector: "Metals & Mining" },
  { symbol: "NSLNISP", sector: "Metals & Mining" },
  { symbol: "NTPC", sector: "Power" },
  { symbol: "NTPCGREEN", sector: "Power" },
  { symbol: "NUVAMA", sector: "Financial Services" },
  { symbol: "NUVOCO", sector: "Construction Materials" },
  { symbol: "NYKAA", sector: "Consumer Services" },
  { symbol: "OBEROIRLTY", sector: "Realty" },
  { symbol: "OFSS", sector: "Information Technology" },
  { symbol: "OIL", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "OLAELEC", sector: "Automobile and Auto Components" },
  { symbol: "OLECTRA", sector: "Automobile and Auto Components" },
  { symbol: "ONESOURCE", sector: "Healthcare" },
  { symbol: "ONGC", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "PAGEIND", sector: "Textiles" },
  { symbol: "PATANJALI", sector: "Fast Moving Consumer Goods" },
  { symbol: "PAYTM", sector: "Financial Services" },
  { symbol: "PCBL", sector: "Chemicals" },
  { symbol: "PERSISTENT", sector: "Information Technology" },
  { symbol: "PETRONET", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "PFC", sector: "Financial Services" },
  { symbol: "PFIZER", sector: "Healthcare" },
  { symbol: "PGEL", sector: "Consumer Durables" },
  { symbol: "PGHH", sector: "Fast Moving Consumer Goods" },
  { symbol: "PHOENIXLTD", sector: "Realty" },
  { symbol: "PIDILITIND", sector: "Chemicals" },
  { symbol: "PIIND", sector: "Chemicals" },
  { symbol: "PNB", sector: "Financial Services" },
  { symbol: "PNBHOUSING", sector: "Financial Services" },
  { symbol: "POLICYBZR", sector: "Financial Services" },
  { symbol: "POLYCAB", sector: "Capital Goods" },
  { symbol: "POLYMED", sector: "Healthcare" },
  { symbol: "POONAWALLA", sector: "Financial Services" },
  { symbol: "POWERGRID", sector: "Power" },
  { symbol: "POWERINDIA", sector: "Capital Goods" },
  { symbol: "PPLPHARMA", sector: "Healthcare" },
  { symbol: "PRAJIND", sector: "Capital Goods" },
  { symbol: "PREMIERENE", sector: "Capital Goods" },
  { symbol: "PRESTIGE", sector: "Realty" },
  { symbol: "PTCIL", sector: "Capital Goods" },
  { symbol: "PVRINOX", sector: "Media Entertainment & Publication" },
  { symbol: "RADICO", sector: "Fast Moving Consumer Goods" },
  { symbol: "RAILTEL", sector: "Telecommunication" },
  { symbol: "RAINBOW", sector: "Healthcare" },
  { symbol: "RAMCOCEM", sector: "Construction Materials" },
  { symbol: "RBLBANK", sector: "Financial Services" },
  { symbol: "RCF", sector: "Chemicals" },
  { symbol: "RECLTD", sector: "Financial Services" },
  { symbol: "REDINGTON", sector: "Services" },
  { symbol: "RELIANCE", sector: "Oil Gas & Consumable Fuels" },
  { symbol: "RELINFRA", sector: "Power" },
  { symbol: "RHIM", sector: "Capital Goods" },
  { symbol: "RITES", sector: "Construction" },
  { symbol: "RKFORGE", sector: "Automobile and Auto Components" },
  { symbol: "RPOWER", sector: "Power" },
  { symbol: "RRKABEL", sector: "Capital Goods" },
  { symbol: "RVNL", sector: "Construction" },
  { symbol: "SAGILITY", sector: "Information Technology" },
  { symbol: "SAIL", sector: "Metals & Mining" },
  { symbol: "SAILIFE", sector: "Healthcare" },
  { symbol: "SAMMAANCAP", sector: "Financial Services" },
  { symbol: "SAPPHIRE", sector: "Consumer Services" },
  { symbol: "SARDAEN", sector: "Metals & Mining" },
  { symbol: "SAREGAMA", sector: "Media Entertainment & Publication" },
  { symbol: "SBFC", sector: "Financial Services" },
  { symbol: "SBICARD", sector: "Financial Services" },
  { symbol: "SBILIFE", sector: "Financial Services" },
  { symbol: "SBIN", sector: "Financial Services" },
  { symbol: "SCHAEFFLER", sector: "Automobile and Auto Components" },
  { symbol: "SCHNEIDER", sector: "Capital Goods" },
  { symbol: "SCI", sector: "Services" },
  { symbol: "SHREECEM", sector: "Construction Materials" },
  { symbol: "SHRIRAMFIN", sector: "Financial Services" },
  { symbol: "SHYAMMETL", sector: "Capital Goods" },
  { symbol: "SIEMENS", sector: "Capital Goods" },
  { symbol: "SIGNATURE", sector: "Realty" },
  { symbol: "SJVN", sector: "Power" },
  { symbol: "SOBHA", sector: "Realty" },
  { symbol: "SOLARINDS", sector: "Chemicals" },
  { symbol: "SONACOMS", sector: "Automobile and Auto Components" },
  { symbol: "SONATSOFTW", sector: "Information Technology" },
  { symbol: "SRF", sector: "Chemicals" },
  { symbol: "STARHEALTH", sector: "Financial Services" },
  { symbol: "SUMICHEM", sector: "Chemicals" },
  { symbol: "SUNDARMFIN", sector: "Financial Services" },
  { symbol: "SUNDRMFAST", sector: "Automobile and Auto Components" },
  { symbol: "SUNPHARMA", sector: "Healthcare" },
  { symbol: "SUNTV", sector: "Media Entertainment & Publication" },
  { symbol: "SUPREMEIND", sector: "Capital Goods" },
  { symbol: "SUZLON", sector: "Capital Goods" },
  { symbol: "SWANCORP", sector: "Chemicals" },
  { symbol: "SWIGGY", sector: "Consumer Services" },
  { symbol: "SYNGENE", sector: "Healthcare" },
  { symbol: "SYRMA", sector: "Capital Goods" },
  { symbol: "TARIL", sector: "Capital Goods" },
  { symbol: "TATACHEM", sector: "Chemicals" },
  { symbol: "TATACOMM", sector: "Telecommunication" },
  { symbol: "TATACONSUM", sector: "Fast Moving Consumer Goods" },
  { symbol: "TATAELXSI", sector: "Information Technology" },
  { symbol: "TATAINVEST", sector: "Financial Services" },
  { symbol: "TATAPOWER", sector: "Power" },
  { symbol: "TATASTEEL", sector: "Metals & Mining" },
  { symbol: "TATATECH", sector: "Information Technology" },
  { symbol: "TBOTEK", sector: "Consumer Services" },
  { symbol: "TCS", sector: "Information Technology" },
  { symbol: "TECHM", sector: "Information Technology" },
  { symbol: "TECHNOE", sector: "Construction" },
  { symbol: "TEJASNET", sector: "Telecommunication" },
  { symbol: "THELEELA", sector: "Consumer Services" },
  { symbol: "THERMAX", sector: "Capital Goods" },
  { symbol: "TIINDIA", sector: "Automobile and Auto Components" },
  { symbol: "TIMKEN", sector: "Capital Goods" },
  { symbol: "TITAGARH", sector: "Capital Goods" },
  { symbol: "TITAN", sector: "Consumer Durables" },
  { symbol: "TMPV", sector: "Automobile and Auto Components" },
  { symbol: "TORNTPHARM", sector: "Healthcare" },
  { symbol: "TORNTPOWER", sector: "Power" },
  { symbol: "TRENT", sector: "Consumer Services" },
  { symbol: "TRIDENT", sector: "Textiles" },
  { symbol: "TRITURBINE", sector: "Capital Goods" },
  { symbol: "TRIVENI", sector: "Fast Moving Consumer Goods" },
  { symbol: "TTML", sector: "Telecommunication" },
  { symbol: "TVSMOTOR", sector: "Automobile and Auto Components" },
  { symbol: "UBL", sector: "Fast Moving Consumer Goods" },
  { symbol: "UCOBANK", sector: "Financial Services" },
  { symbol: "ULTRACEMCO", sector: "Construction Materials" },
  { symbol: "UNIONBANK", sector: "Financial Services" },
  { symbol: "UNITDSPR", sector: "Fast Moving Consumer Goods" },
  { symbol: "UNOMINDA", sector: "Automobile and Auto Components" },
  { symbol: "UPL", sector: "Chemicals" },
  { symbol: "USHAMART", sector: "Capital Goods" },
  { symbol: "UTIAMC", sector: "Financial Services" },
  { symbol: "VBL", sector: "Fast Moving Consumer Goods" },
  { symbol: "VEDL", sector: "Metals & Mining" },
  { symbol: "VENTIVE", sector: "Consumer Services" },
  { symbol: "VGUARD", sector: "Consumer Durables" },
  { symbol: "VIJAYA", sector: "Healthcare" },
  { symbol: "VMM", sector: "Consumer Services" },
  { symbol: "VOLTAS", sector: "Consumer Durables" },
  { symbol: "VTL", sector: "Textiles" },
  { symbol: "WAAREEENER", sector: "Capital Goods" },
  { symbol: "WELCORP", sector: "Capital Goods" },
  { symbol: "WELSPUNLIV", sector: "Textiles" },
  { symbol: "WHIRLPOOL", sector: "Consumer Durables" },
  { symbol: "WIPRO", sector: "Information Technology" },
  { symbol: "WOCKPHARMA", sector: "Healthcare" },
  { symbol: "YESBANK", sector: "Financial Services" },
  { symbol: "ZEEL", sector: "Media Entertainment & Publication" },
  { symbol: "ZENSARTECH", sector: "Information Technology" },
  { symbol: "ZENTEC", sector: "Capital Goods" },
  { symbol: "ZFCVINDIA", sector: "Automobile and Auto Components" },
  { symbol: "ZYDUSLIFE", sector: "Healthcare" }
];
